import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Providers } from './Providers';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              success: {
                style: {
                  background: 'green',
                  color: 'white',
                },
                iconTheme: {
                  primary: 'white',
                  secondary: 'green',
                },
              },
              error: {
                style: {
                  background: 'red',
                  color: 'white',
                },
                iconTheme: {
                  primary: 'white',
                  secondary: 'red',
                },
              },
              duration: 3000,
              style: {
                border: '1px solid #713200',
                padding: '16px',
                color: '#713200',
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}